image: python:latest

stages:
  - test
  - docs
  - publish

coverage:
  stage: test
  script:
    - pip install -e .[dev]
    - pytest tests --cov=src/pyjapi --cov-report=term
    - coverage html
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov

build_docs:
  stage: docs
  script:
    - pip install -e .[dev,docs]
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
  only:
    - master
    - staging

pages:
  stage: publish
  dependencies:
    - coverage
    - build_docs
  script:
    - mv docs/build/html public
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
    - staging

package:
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://git01.iis.fhg.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  when: manual
  only:
   - master
   - staging
