image: python:latest

stages:
  - demo
  - test
  - build
  - publish

build_server:
  image: git01.iis.fhg.de:5005/ks-ip-lib/software/libjapi-demo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: demo
  script:
    - cd ext/libjapi-demo && mkdir build && cd build && cmake3 ../ && make && mv demo-static ../../../demo-static
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - demo-static

coverage:
  stage: test
  needs:
    - build_server
  script:
    - pip install hatch
    - mkdir -p ext/libjapi-demo/build
    - mv demo-static ext/libjapi-demo/build/demo-static
    - ls ext/libjapi-demo/build
    - hatch run dev:coverage
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - build/coverage

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build_docs:
  stage: build
  script:
    - pip install hatch
    - hatch run docs:html
  artifacts:
    paths:
      - build/docs/html
  only:
    - main
    - staging

pages:
  stage: publish
  dependencies:
    - coverage
    - build_docs
  script:
    - mv build/docs/html public
    - mv build/coverage public/.
  artifacts:
    paths:
      - public
  only:
    - main
    - staging

package:
  stage: build
  script:
    - pip install hatch
    - hatch build --clean
  only:
    - main
    - staging
  artifacts:
    paths:
      - dist

pypi:
  stage: publish
  dependencies:
    - package
  script:
    - pip install hatch
    - hatch publish -n
  when: manual
  only:
    - tags
