image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - publish

demo_server:
  image: git01.iis.fhg.de:5005/ks-ip-lib/software/libjapi-demo:latest
  stage: test
  script:
    - cd ext/libjapi-demo && mkdir build && cd build && cmake3 ../ && make
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ext/libjapi-demo/build

coverage:
  stage: test
  dependencies:
    - demo_server
  script:
    - pip install hatch
    - ls ext/libjapi-demo/build
    - hatch run dev:coverage
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - build/coverage

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build_docs:
  stage: build
  script:
    - pip install hatch
    - hatch run docs:html
  artifacts:
    paths:
      - build/docs/html
  only:
    - main
    - staging

pages:
  stage: publish
  dependencies:
    - coverage
    - build_docs
  script:
    - mv build/docs/html public
    - mv build/coverage public/.
  artifacts:
    paths:
      - public
  only:
    - main
    - staging

package:
  stage: build
  script:
    - pip install hatch
    - hatch build --clean
  only:
    - main
    - staging
  artifacts:
    paths:
      - dist

pypi:
  stage: publish
  dependencies:
    - package
  script:
    - pip install hatch
    - hatch publish -n
  when: manual
  only:
    - tags
